server:
  port: 9100

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 'a'
        url: jdbc:postgresql://localhost:5432/company
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        show-sql: false
        properties:
            hibernate:
                temp:
                    :use_jdbc_metadata_defaults: false
                    
spring:
    liquibase:
        enabled: true
        change-log: classpath:/data/changelog/db.changelog-master.xml
        

authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
      id: orders
